#!/usr/bin/env python3
"""MBXCART.BIN -> tang/console138k/st_helper_cart_rom.v (a case ROM, so no
$readmemh path issues in Gowin). Run by build.sh."""
import sys
data = open(sys.argv[1], 'rb').read()
if len(data) % 2: data += b'\xff'
words = [(data[i] << 8) | data[i+1] for i in range(0, len(data), 2)]
assert len(words) <= 2048, "cartridge image larger than the 4 KB window"
out = []
out.append("// GENERATED by helper_fw/st_test/mkcart.py from mbxcart.s - do not edit.")
out.append("// ST_HELPER_CART: mailbox self-test cartridge, $FA0000-$FA0FFF (%d bytes)." % len(data))
out.append("// 16-bit asynchronous ROM: the GSTMCU acknowledges ROM4 ($FAxxxx) reads")
out.append("// at once, like the TOS ROM, so the data must follow the address.")
out.append("module st_helper_cart_rom (")
out.append("    input  wire [11:1] a,")
out.append("    output reg  [15:0] d")
out.append(");")
out.append("    always @* begin")
out.append("        case (a)")
for i, w in enumerate(words):
    out.append("        11'd%d: d = 16'h%04X;" % (i, w))
out.append("        default: d = 16'hFFFF;")
out.append("        endcase")
out.append("    end")
out.append("endmodule")
open(sys.argv[2], 'w').write("\n".join(out) + "\n")
print("%s: %d words" % (sys.argv[2], len(words)))
