// cpu030_st_bridge.v - WF68K30L (68030) on the Atari ST 68000 bus
//
// FalconFPGA, Atarist_030_wip, first 030 integration (no add-ons: no TT-RAM,
// IDE, SPI or autoconfig). Drops into atarist/atarist.v in place of fx68k,
// with the same port names where they make sense, plus clk_cpu.
//
// ===========================================================================
// CREDIT: Stephen J. Leary (TerribleFire)
//
// This bridge is based on Stephen J. Leary's TerribleFire TF534 accelerator,
// Copyright (C) 2016-2019, Stephen J. Leary, GPL-2.0-only. His published
// TF534 RTL, built with its ATARI switch, is the design this file follows:
//   rtl/bus_top.v    030 -> 68000 bus translation, UDS/LDS equations,
//                    CPU-space interrupt acknowledge / autovector decode
//   rtl/arb.v        bus arbitration ("only pass BG when the 68000 side is
//                    idle")
//   rtl/m6800.v      6800 peripheral cycles: E clock (10-state counter),
//                    VMA and VPA
//   rtl/bus_delay.v  DTACK delay before it reaches the 030
// Every place in this file where his logic is used is marked "TF534".
// This phase of the FalconFPGA work would have been much more difficult
// without his design. Thank you, Stephen.
// ===========================================================================
//
// Adaptation: Copyright (C) 2026 FalconFPGA project (dave-1024).
// The TF534 logic (asynchronous CPLD style) is re-expressed here as a
// synchronous clk_32 design. The 68000 bus phase timing (which enable
// edge moves which strobe) is made to match the ST's fx68k core so that the
// GSTMCU/shifter/MFP see the same cycles as before (written from the
// behaviour, no fx68k code is used).
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; version 2 only (as TF534). See LICENSE-GPL2-TF534.
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
// The CPU itself (wf68k30L_*.vhd, WF68K30L IP core, (C) Wolfgang Foerster,
// CERN OHL 1.2, with the rigsdram audit fixes) is used unmodified.
//
// ---------------------------------------------------------------------------
// Structure
//
//   clk_cpu domain (the 030 uses BOTH edges of clk_cpu)
//     WF68K30L_TOP
//     front end: on the first rising clk_cpu edge that sees ASn low after a
//       rising edge that saw ASn high (i.e. at the start of 030 S2) latch
//       address, SIZE, RW, FC, RMC and write data and toggle req_t.
//       c_open drops again on the rising edge that sees ASn high (S5/idle),
//       which gates every termination signal off before the next cycle's
//       first falling-edge sample, whatever the clock ratio.
//   clk_32 domain (the ST chipset)
//     req_t is synchronised (SYNC_STAGES flops), then one 68000 bus cycle
//     is run on the ST bus with the fx68k phase timing on mhz8_en1/en2
//     (DTACK/VPA+E/BERR termination, arbitration BR/BG/BGACK, E and VMA).
//     At the end (S6, en2: the same edge where the 68000 negates AS and
//     latches data) the read data and the termination for the 030
//     (DSACKn="01" = 16-bit port, AVECn for an autovectored IACK, BERRn)
//     are registered together with the request tag.
//
//   This is a request/acknowledge handshake, so clk_cpu may later be made
//   faster than the 8 MHz ST bus ("accelerated ST") without changing the ST
//   side. For the first integration clk_cpu is 8 MHz from the same PLL as
//   clk_32 (related clocks). The returning tag, DSACK and read word are still
//   synchronised into clk_cpu: a combinational sample of the clk_32 register
//   was early, so the first fetch was not the ROM word.
//
// Bus sizing: the 030 does its own dynamic bus sizing. Every ST cycle is
// answered as a 16-bit port (DSACKn = "01"): even byte on D31:24, odd byte on
// D23:16, words on D31:16. A long or a misaligned word becomes several ST
// cycles, generated by the 030 itself.
// Addresses: A23:1 only (A31:24 ignored), so the 030 sees the ST's 24-bit
// aliasing like a real ST.
// CPU space (FC=7): A19:16=F is an interrupt acknowledge and runs a real ST
// IACK cycle (MFP vector via DTACK, or VPA -> AVECn autovector). Any other
// CPU-space cycle (breakpoint, coprocessor, MMU) gets BERR at once without an
// ST cycle.
// ---------------------------------------------------------------------------

`default_nettype none

module cpu030_st_bridge #(
    parameter integer SYNC_STAGES = 2,    // clk_cpu -> clk_32 request synchroniser
    parameter integer RESET_HOLD  = 128   // RESET_INn+HALT_INn low, clk_cpu cycles (>=16)
) (
    input  wire        clk,         // clk_32 (ST chipset clock)
    input  wire        clk_cpu,     // 030 clock (8 MHz, related to clk_32)
    input  wire        extReset,    // ST reset (clk_32 domain)
    input  wire        pwrUp,       // power-up reset (clk_32 domain)
    input  wire        enPhi1,      // mhz8_en1
    input  wire        enPhi2,      // mhz8_en2

    output wire        eRWn,
    output wire        ASn,
    output wire        LDSn,
    output wire        UDSn,
    output reg         E,
    output wire        VMAn,
    output wire        FC0,
    output wire        FC1,
    output wire        FC2,
    output reg         BGn,
    output wire        oRESETn,
    output wire        oHALTEDn,
    input  wire        DTACKn,
    input  wire        VPAn,
    input  wire        BERRn,
    input  wire        HALTn,       // unused (tied high in atarist.v)
    input  wire        BRn,
    input  wire        BGACKn,
    input  wire        IPL0n,
    input  wire        IPL1n,
    input  wire        IPL2n,
    input  wire [15:0] iEdb,
    output wire [15:0] oEdb,
    output wire [23:1] eab,
    output reg         rom_fetch   // latched first ROM-window cycle, cleared by reset
);

    // =====================================================================
    // clk_cpu domain: CPU reset and the 030 core
    // =====================================================================
    // RESET_INn and HALT_INn are held low together for RESET_HOLD clk_cpu
    // cycles after the ST reset (or power-up) ends. RESET_OUT (RESET
    // instruction) is not fed back into the CPU; it goes to the ST as
    // oRESETn like fx68k's.
    localparam [7:0] RHOLD = RESET_HOLD;
    (* syn_preserve = 1 *) reg [1:0] rst_sync = 2'b11;
    reg [7:0]  rst_cnt   = 8'd0;
    reg        cpu_rst_n = 1'b0;
    wire       st_rst    = extReset | pwrUp;

    always @(posedge clk_cpu) begin
        rst_sync <= {rst_sync[0], st_rst};
        if (rst_sync[1]) begin
            rst_cnt   <= 8'd0;
            cpu_rst_n <= 1'b0;
        end else if (rst_cnt != RHOLD) begin
            rst_cnt   <= rst_cnt + 8'd1;
            cpu_rst_n <= 1'b0;
        end else begin
            cpu_rst_n <= 1'b1;
        end
    end

    wire [31:0] cpu_adr, cpu_dout;
    wire [31:0] cpu_din;
    wire [1:0]  cpu_size, cpu_dsackn;
    wire [2:0]  cpu_fc;
    wire        cpu_asn, cpu_rwn, cpu_rmcn, cpu_dsn;
    wire        cpu_reset_out, cpu_halt_outn;
    wire        cpu_berrn, cpu_avecn;
    reg  [2:0]  ipl_r = 3'b111;

    WF68K30L_TOP i_wf68k30l (
        .CLK       ( clk_cpu       ),
        .ADR_OUT   ( cpu_adr       ),
        .DATA_IN   ( cpu_din       ),
        .DATA_OUT  ( cpu_dout      ),
        .DATA_EN   (               ),
        .BERRn     ( cpu_berrn     ),
        .RESET_INn ( cpu_rst_n     ),
        .RESET_OUT ( cpu_reset_out ),
        .HALT_INn  ( cpu_rst_n     ),
        .HALT_OUTn ( cpu_halt_outn ),
        .FC_OUT    ( cpu_fc        ),
        .AVECn     ( cpu_avecn     ),
        .IPLn      ( ipl_r         ),
        .IPENDn    (               ),
        .DSACKn    ( cpu_dsackn    ),
        .SIZE      ( cpu_size      ),
        .ASn       ( cpu_asn       ),
        .RWn       ( cpu_rwn       ),
        .RMCn      ( cpu_rmcn      ),
        .DSn       ( cpu_dsn       ),
        .ECSn      (               ),
        .OCSn      (               ),
        .DBENn     (               ),
        .BUS_EN    (               ),
        .STERMn    ( 1'b1          ),
        .STATUSn   (               ),
        .REFILLn   (               ),
        .BRn       ( 1'b1          ),   // arbitration is done on the ST side
        .BGn       (               ),
        .BGACKn    ( 1'b1          )
    );

    // ---- front end: request capture (rising clk_cpu) ----------------------
    reg        c_open  = 1'b0;
    reg        c_req_t = 1'b0;
    reg [23:0] c_adr   = 24'd0;
    reg [1:0]  c_size  = 2'b00;
    reg        c_rwn   = 1'b1;
    reg [2:0]  c_fc    = 3'd0;
    reg [15:0] c_wdata = 16'd0;

    always @(posedge clk_cpu) begin
        if (!cpu_rst_n || cpu_asn) begin
            c_open <= 1'b0;
        end else if (!c_open) begin
            // first rising edge with AS low: 030 S1 -> S2. Address, SIZE,
            // RW, FC and (for writes) the data mux output are valid.
            c_open  <= 1'b1;
            c_req_t <= ~c_req_t;
            c_adr   <= cpu_adr[23:0];     // A31:24 ignored: 24-bit ST bus
            c_size  <= cpu_size;
            c_rwn   <= cpu_rwn;
            c_fc    <= cpu_fc;
            c_wdata <= cpu_dout[31:16];   // 16-bit port: D31:24 even, D23:16 odd
        end
    end

    // ---- terminations back to the 030 ------------------------------------
    // s_* are written at S6 en2, after the ST cycle has finished. They are
    // clk_32 registers. Two flops in clk_cpu hold the word until that write
    // has crossed, and the data flop is the same depth as the tag so the
    // 030 cannot see DSACK against the previous word.
    reg        s_tag    = 1'b0;
    reg        s_dsack  = 1'b0;
    reg        s_avec   = 1'b0;
    reg        s_berr   = 1'b0;
    reg [15:0] s_rdata  = 16'hffff;

    (* syn_preserve = 1 *) reg [1:0] tag_sync = 2'b0;
    (* syn_preserve = 1 *) reg [1:0] dsack_sync = 2'b0;
    (* syn_preserve = 1 *) reg [1:0] avec_sync = 2'b0;
    (* syn_preserve = 1 *) reg [1:0] berr_sync = 2'b0;
    reg [15:0] rdata_hold = 16'hffff;
    reg [15:0] rdata_sync = 16'hffff;

    always @(posedge clk_cpu) begin
        if (!cpu_rst_n) begin
            tag_sync   <= 2'b0;
            dsack_sync <= 2'b0;
            avec_sync  <= 2'b0;
            berr_sync  <= 2'b0;
            rdata_hold <= 16'hffff;
            rdata_sync <= 16'hffff;
        end else begin
            tag_sync   <= {tag_sync[0], s_tag};
            dsack_sync <= {dsack_sync[0], s_dsack};
            avec_sync  <= {avec_sync[0], s_avec};
            berr_sync  <= {berr_sync[0], s_berr};
            rdata_hold <= s_rdata;
            rdata_sync <= rdata_hold;
        end
    end

    wire term_ok = c_open & (tag_sync[1] == c_req_t);
    assign cpu_dsackn = (term_ok & dsack_sync[1]) ? 2'b01 : 2'b11;
    assign cpu_avecn  = ~(term_ok & avec_sync[1]);
    assign cpu_berrn  = ~(term_ok & berr_sync[1]);
    assign cpu_din    = {rdata_sync, rdata_sync};

    // =====================================================================
    // clk_32 domain: the 68000 side
    // =====================================================================
    always @(posedge clk) ipl_r <= {IPL2n, IPL1n, IPL0n};

    (* syn_preserve = 1 *) reg [SYNC_STAGES-1:0] req_sync = {SYNC_STAGES{1'b0}};
    (* syn_preserve = 1 *) reg [1:0] rmc_sync = 2'b11;
    (* syn_preserve = 1 *) reg [1:0] rsto_sync = 2'b00;
    (* syn_preserve = 1 *) reg [1:0] hlt_sync = 2'b11;
    always @(posedge clk) begin
        req_sync  <= {req_sync[SYNC_STAGES-2:0], c_req_t};
        rmc_sync  <= {rmc_sync[0], cpu_rmcn};
        rsto_sync <= {rsto_sync[0], cpu_reset_out};
        hlt_sync  <= {hlt_sync[0], cpu_halt_outn};
    end
    wire req_now  = req_sync[SYNC_STAGES-1];
    assign oRESETn  = ~rsto_sync[1];
    assign oHALTEDn = hlt_sync[1];
    wire rmc_lock = ~rmc_sync[1];

    reg  s_seen = 1'b0;
    wire pending = (req_now != s_seen);
    // request fields are stable: they were written together with the toggle
    // TF534 (Stephen J. Leary), rtl/bus_top.v: CPU space (FC=7) with A19:16=F
    // is an interrupt acknowledge; other CPU-space cycles are not passed on.
    wire req_cpu_space = (c_fc == 3'b111);
    wire req_iack      = req_cpu_space & (c_adr[19:16] == 4'hF);
    wire req_bad_space = req_cpu_space & ~req_iack;

    // ---- input sampling like a 68000 (DTACK/BERR on en2, VPA/BR/BGACK en1)
    // TF534 (Stephen J. Leary), rtl/bus_delay.v: DTACK is delayed (one stage
    // in its ATARI build) before the 030 is terminated; here it is registered.
    reg rDtack = 1'b1, rBerr = 1'b1, Vpai = 1'b1, BRi = 1'b1, BgackI = 1'b1;
    always @(posedge clk) begin
        if (enPhi2) begin
            rDtack <= DTACKn;
            rBerr  <= BERRn;
        end
        if (enPhi1) begin
            Vpai   <= VPAn;
            BRi    <= BRn;
            BgackI <= BGACKn;
        end
    end

    // ---- bus phases (advance on en1): IDLE, S0, S2, S4 (waits), S6 ---------
    localparam [2:0] P_IDLE = 3'd0, P_S0 = 3'd1, P_S2 = 3'd2, P_S4 = 3'd3, P_S6 = 3'd4;
    localparam [1:0] R_DSACK = 2'd0, R_AVEC = 2'd1, R_BERR = 2'd2;

    reg [2:0]  phase  = P_IDLE;
    reg        rAS = 1'b1, rUDS = 1'b1, rLDS = 1'b1, rRWn = 1'b1;
    reg [23:1] r_adr  = 23'h7fffff;
    reg [2:0]  r_fc   = 3'b111;
    reg [15:0] r_dout = 16'hffff;
    reg        r_write = 1'b0, r_uds = 1'b0, r_lds = 1'b0, r_iack = 1'b0, r_tag = 1'b0;
    reg        addr_oe = 1'b0;
    reg [1:0]  r_res  = R_DSACK;
    reg        iStop  = 1'b0;
    reg [3:0]  eCntr  = 4'd0;
    reg        rVma   = 1'b1;

    // arbitration (68000 style, BG changes on en1, state on en2)
    // TF534 (Stephen J. Leary), rtl/arb.v: BG is only passed to another bus
    // master when the 68000 side is idle (bg_block below).
    localparam [1:0] A_IDLE = 2'd0, A_GRANT = 2'd1, A_BUSY = 2'd2;
    reg [1:0] arb = A_IDLE;
    reg [1:0] arb_nx;
    reg       granting = 1'b0;
    wire bg_block  = (phase == P_S0) | rmc_lock;   // no grant while a cycle starts or during RMC
    wire bus_avail = BRi & BgackI & (arb == A_IDLE);

    always @* begin
        arb_nx = arb;
        case (arb)
        A_IDLE:  if (~BgackI)               arb_nx = A_BUSY;    // taken without BR
                 else if (~BRi & ~bg_block) arb_nx = A_GRANT;
        A_GRANT: if (~BgackI)               arb_nx = A_BUSY;    // master took the bus
                 else if (BRi)              arb_nx = A_IDLE;    // request withdrawn
        A_BUSY:  if (BgackI)                arb_nx = (~BRi & ~bg_block) ? A_GRANT : A_IDLE;
        default:                            arb_nx = A_IDLE;
        endcase
    end
    // BG is asserted in GRANT, and also in BUSY when another master already
    // requests again (68000 behaviour for chained masters)
    wire grant_nx = (arb_nx == A_GRANT) | ((arb_nx == A_BUSY) & ~BRi & ~bg_block);
    wire can_start = pending & ~req_bad_space & bus_avail;
    // A23:20 == E is the 256K map. FC/FD/FE is the 192K map.
    wire req_rom = (c_adr[23:20] == 4'hE) |
                   (c_adr[23:16] == 8'hFC) | (c_adr[23:16] == 8'hFD) |
                   (c_adr[23:16] == 8'hFE);


    // UDS/LDS from A0 and SIZE: 16-bit port
    // TF534 (Stephen J. Leary), rtl/bus_top.v: these equations are his.
    wire req_uds = ~c_adr[0];
    wire req_lds =  c_adr[0] | (c_size != 2'b01);

    assign ASn  = rAS;
    assign UDSn = rUDS;
    assign LDSn = rLDS;
    assign eRWn = rRWn;
    assign VMAn = rVma;
    assign {FC2, FC1, FC0} = r_fc;
    assign eab  = r_adr;
    assign oEdb = r_dout;

    wire xVma = ~rVma & (eCntr == 4'd8);

    always @(posedge clk) begin
        if (pwrUp) begin
            E     <= 1'b0;
            eCntr <= 4'd0;
            rVma  <= 1'b1;
        end else begin
            // E: 10 en2 periods, 6 low / 4 high (68000 E clock)
            // TF534 (Stephen J. Leary), rtl/m6800.v: 10-state E counter, VMA
            // asserted for VPA cycles and the cycle ended at the E edge.
            if (enPhi2) begin
                if (eCntr == 4'd9)      E <= 1'b0;
                else if (eCntr == 4'd5) E <= 1'b1;
                eCntr <= (eCntr == 4'd9) ? 4'd0 : eCntr + 4'd1;
            end
            if (enPhi2 & addr_oe & ~Vpai & (eCntr == 4'd3))
                rVma <= 1'b0;
            else if (enPhi1 & (eCntr == 4'd0))
                rVma <= 1'b1;
        end
    end

    always @(posedge clk) begin
        if (extReset | pwrUp) begin
            phase   <= P_IDLE;
            rAS     <= 1'b1;
            rUDS    <= 1'b1;
            rLDS    <= 1'b1;
            rRWn    <= 1'b1;
            addr_oe <= 1'b0;
            iStop   <= 1'b0;
            s_seen  <= req_now;
            s_dsack <= 1'b0;
            s_avec  <= 1'b0;
            s_berr  <= 1'b0;
            arb     <= A_IDLE;
            granting <= 1'b0;
            BGn       <= 1'b1;
            rom_fetch <= 1'b0;
        end else begin
            // ---- arbitration: state on en2, BG output on en1 ----
            if (enPhi2) begin
                arb      <= arb_nx;
                granting <= grant_nx;
            end
            if (enPhi1)
                BGn <= ~granting;

            // ---- CPU-space cycles other than IACK: BERR, no ST cycle ----
            if (pending & req_bad_space) begin
                s_seen  <= req_now;
                s_tag   <= req_now;
                s_dsack <= 1'b0;
                s_avec  <= 1'b0;
                s_berr  <= 1'b1;
            end

            // ---- termination sampling like the 68000 ----
            if (enPhi2)
                iStop <= xVma | (Vpai & ~rBerr);

            if (enPhi2 & (phase == P_S0))
                addr_oe <= 1'b1;

            // ---- S6 en2: negate AS/DS, latch data, answer the 030 ----
            if (enPhi2 & (phase == P_S6)) begin
                rAS     <= 1'b1;
                rUDS    <= 1'b1;
                rLDS    <= 1'b1;
                s_rdata <= iEdb;
                s_tag   <= r_tag;
                s_dsack <= (r_res == R_DSACK);
                s_avec  <= (r_res == R_AVEC);
                s_berr  <= (r_res == R_BERR);
            end

            if (enPhi1) begin
                case (phase)
                P_S0: begin
                    phase <= P_S2;
                    rAS   <= 1'b0;
                    if (r_write) rRWn <= 1'b0;
                    else begin
                        rUDS <= ~r_uds;
                        rLDS <= ~r_lds;
                    end
                end
                P_S2: begin
                    phase <= P_S4;
                    if (r_write) begin
                        rUDS <= ~r_uds;
                        rLDS <= ~r_lds;
                    end
                end
                P_S4: begin
                    if (~rDtack | iStop) begin
                        phase <= P_S6;
                        if (~rDtack)    r_res <= R_DSACK;
                        else if (~rVma) r_res <= r_iack ? R_AVEC : R_DSACK; // VPA/E cycle
                        else            r_res <= R_BERR;
                    end
                end
                default: ;   // P_IDLE / P_S6 handled below
                endcase

                if (phase == P_S6) begin
                    rRWn    <= 1'b1;
                    addr_oe <= 1'b0;
                    phase   <= P_IDLE;
                end

                if ((phase == P_IDLE | phase == P_S6) & can_start) begin
                    if (req_rom) rom_fetch <= 1'b1;
                    // accept the 030 request: 68000 S0
                    phase   <= P_S0;
                    s_seen  <= req_now;
                    s_dsack <= 1'b0;
                    s_avec  <= 1'b0;
                    s_berr  <= 1'b0;
                    r_tag   <= req_now;
                    r_adr   <= c_adr[23:1];
                    r_fc    <= c_fc;
                    r_write <= ~c_rwn;
                    r_dout  <= c_wdata;
                    r_uds   <= req_uds;
                    r_lds   <= req_lds;
                    r_iack  <= req_iack;
                end
            end
        end
    end

endmodule

`default_nettype wire
