// cpu030_st_bridge.v - WF68K30L (68030) on the Atari ST 68000 bus
//
// FalconFPGA, Atarist_030_wip, first 030 integration (no add-ons: no TT-RAM,
// IDE, SPI or autoconfig). Drops into atarist/atarist.v in place of fx68k,
// with the same port names where they make sense, plus clk_cpu.
//
// ===========================================================================
// CREDIT: Stephen J. Leary (TerribleFire)
//
// This bridge is based on Stephen J. Leary's TerribleFire TF534 accelerator,
// Copyright (C) 2016-2019, Stephen J. Leary, GPL-2.0-only. His published
// TF534 RTL, built with its ATARI switch, is the design this file follows:
//   rtl/bus_top.v    030 -> 68000 bus translation, UDS/LDS equations,
//                    CPU-space interrupt acknowledge / autovector decode
//   rtl/arb.v        bus arbitration ("only pass BG when the 68000 side is
//                    idle")
//   rtl/m6800.v      6800 peripheral cycles: E clock (10-state counter),
//                    VMA and VPA
//   rtl/bus_delay.v  DTACK delay before it reaches the 030
// Every place in this file where his logic is used is marked "TF534".
// This phase of the FalconFPGA work would have been much more difficult
// without his design. Thank you, Stephen.
// ===========================================================================
//
// Adaptation: Copyright (C) 2026 FalconFPGA project (dave-1024).
// The TF534 logic (asynchronous CPLD style) is re-expressed here as a
// synchronous clk_32 design. The 68000 bus phase timing (which enable
// edge moves which strobe) is made to match the ST's fx68k core so that the
// GSTMCU/shifter/MFP see the same cycles as before (written from the
// behaviour, no fx68k code is used).
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; version 2 only (as TF534). See LICENSE-GPL2-TF534.
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
// The CPU itself (wf68k30L_*.vhd, WF68K30L IP core, (C) Wolfgang Foerster,
// CERN OHL 1.2, with the rigsdram audit fixes and the FalconFPGA fixes listed
// in BUILD_REPORT.md, F55..F58).
//
// ---------------------------------------------------------------------------
// Structure
//
//   clk_cpu / clk_cpu_n (the 030; clk_cpu_n = clk_cpu at 180 degrees from
//     the same PLL, clocks the core's falling-edge registers, CLK_N_EXT = 1)
//     WF68K30L_TOP, CPU reset counter.
//   clk_32 domain (the ST chipset). clk_cpu is phase-locked to clk_32 (same
//   VCO, every clk_cpu/clk_cpu_n edge is a clk_32 rising edge), so the 030's
//   outputs and the bridge registers are exchanged directly as timed
//   related-clock paths, like a TerribleFire board running its 68000 bus
//   synchronously (F58; before, both directions went through 2-flop
//   synchronisers and an ST access took ~1.6 us, now ~0.9 us at 16 MHz):
//     front end: on the first clk_32 edge that sees ASn low, latch address,
//       SIZE, RW, FC and write data and toggle req_t. c_open drops on the
//       clk_32 edge that sees ASn high, which gates every termination off
//       before the 030's next falling-edge sample.
//     one 68000 bus cycle is run on the ST bus with the fx68k phase timing on
//     mhz8_en1/en2 (DTACK/VPA+E/BERR termination, arbitration BR/BG/BGACK, E
//     and VMA). DSACKn="01" (16-bit port) is given on the en2 edge where a
//     68000 samples DTACK (S4) with an 8 MHz clk_cpu (CPU_DIV 4), one phase
//     later (S4 -> S6 en1) with the 16 MHz clk_cpu used on the board
//     (CPU_DIV 2); the read word is latched at S6 en2 (the 68000's latch
//     edge), before the 030 latches it one clk_cpu after its DSACK sample.
//     VPA/E-cycle, autovector (AVECn) and BERR terminations are given at S6
//     en2 together with the request tag.
//
// Bus sizing: the 030 does its own dynamic bus sizing. Every ST cycle is
// answered as a 16-bit port (DSACKn = "01"): even byte on D31:24, odd byte on
// D23:16, words on D31:16. A long or a misaligned word becomes several ST
// cycles, generated by the 030 itself.
// Addresses: A23:1 only (A31:24 ignored), so the 030 sees the ST's 24-bit
// aliasing like a real ST.
// CPU space (FC=7): A19:16=F is an interrupt acknowledge and runs a real ST
// IACK cycle (MFP vector via DTACK, or VPA -> AVECn autovector). Any other
// CPU-space cycle (breakpoint, coprocessor, MMU) gets BERR at once without an
// ST cycle.
// ---------------------------------------------------------------------------

`default_nettype none

module cpu030_st_bridge #(
    parameter integer SYNC_STAGES = 2,    // unused since F58 (no request synchroniser), kept for compatibility
    parameter integer RESET_HOLD  = 128,  // RESET_INn+HALT_INn low, clk_cpu cycles (>=16)
    parameter integer CPU_DIV     = 4     // clk_32 / clk_cpu: 4 = 8 MHz, 2 = 16 MHz (both phase-locked)
) (
    input  wire        clk,         // clk_32 (ST chipset clock)
    input  wire        clk_cpu,     // 030 clock (16 MHz on the board, related to clk_32)
    input  wire        clk_cpu_n,   // 180 degree copy of clk_cpu (PLL): the 030's falling-edge registers
    input  wire        extReset,    // ST reset (clk_32 domain)
    input  wire        pwrUp,       // power-up reset (clk_32 domain)
    input  wire        enPhi1,      // mhz8_en1
    input  wire        enPhi2,      // mhz8_en2

    output wire        eRWn,
    output wire        ASn,
    output wire        ASEn,        // F61: address phase (S0) of a cycle, before ASn (TOS flash read start)
    output wire        LDSn,
    output wire        UDSn,
    output reg         E,
    output wire        VMAn,
    output wire        FC0,
    output wire        FC1,
    output wire        FC2,
    output reg         BGn,
    output wire        oRESETn,
    output wire        oHALTEDn,
    input  wire        DTACKn,
    input  wire        VPAn,
    input  wire        BERRn,
    input  wire        HALTn,       // unused (tied high in atarist.v)
    input  wire        BRn,
    input  wire        BGACKn,
    input  wire        IPL0n,
    input  wire        IPL1n,
    input  wire        IPL2n,
    input  wire [15:0] iEdb,
    output wire [15:0] oEdb,
    output wire [23:1] eab,
    output reg         rom_fetch,  // latched first ROM-window cycle, cleared by reset
    // FalconFPGA DIAG build (diag_overlay.v), observation only
    output wire        dbg_run,    // cpu_rst_n: 030 out of reset (clk_cpu domain)
    output wire        dbg_req,    // req_now: toggles once per 030 AS cycle (clk_32)
    output wire        dbg_dsack,  // s_dsack (clk_32)
    output wire        dbg_berr,   // s_berr (clk_32)
    // FalconFPGA DIAG diag030b/c, observation only (mixed clk_32/clk_cpu,
    // read through 2-FF syncs in the overlay; values are slow or frozen):
    // [167:128] {got, FC2:0, RW, SIZE1:0, bad_space, A31:0 at first BERR} (clk_32)
    // [127:96]  row c: A31:0 of the last bus cycle STARTED by the 030 (clk_cpu)
    // [95:64]   row d: last-start info + termination + CPU pins (clk_cpu)
    // [63:32]   row e: bridge 68000-side state machine (clk_32)
    // [31:0]    row f: {start count 7:0, live last program fetch A23:0} (clk_cpu)
    output wire [167:0] dbg_trace
);

    // =====================================================================
    // clk_cpu domain: CPU reset and the 030 core
    // =====================================================================
    // RESET_INn and HALT_INn are held low together for RESET_HOLD clk_cpu
    // cycles after the ST reset (or power-up) ends. RESET_OUT (RESET
    // instruction) is not fed back into the CPU; it goes to the ST as
    // oRESETn like fx68k's.
    localparam [7:0] RHOLD = RESET_HOLD;
    (* syn_preserve = 1 *) reg [1:0] rst_sync = 2'b11;
    reg [7:0]  rst_cnt   = 8'd0;
    reg        cpu_rst_n = 1'b0;
    wire       st_rst    = extReset | pwrUp;

    always @(posedge clk_cpu) begin
        rst_sync <= {rst_sync[0], st_rst};
        if (rst_sync[1]) begin
            rst_cnt   <= 8'd0;
            cpu_rst_n <= 1'b0;
        end else if (rst_cnt != RHOLD) begin
            rst_cnt   <= rst_cnt + 8'd1;
            cpu_rst_n <= 1'b0;
        end else begin
            cpu_rst_n <= 1'b1;
        end
    end

    wire [31:0] cpu_adr, cpu_dout;
    wire [31:0] cpu_din;
    wire [1:0]  cpu_size, cpu_dsackn;
    wire [2:0]  cpu_fc;
    wire        cpu_asn, cpu_rwn, cpu_rmcn, cpu_dsn;
    wire        cpu_reset_out, cpu_halt_outn;
    wire        cpu_berrn, cpu_avecn;
    wire        cpu_ipendn, cpu_statusn;   // FalconFPGA DIAG
    reg  [2:0]  ipl_r = 3'b111;

`ifdef WF030_NETLIST
    // gate-level simulation (sim/run_unit.sh): the netlist from
    // sim/wf030_syn.tcl is synthesised with CLK_N_EXT = 1 and has no generics
    WF68K30L_TOP i_wf68k30l (
`else
    WF68K30L_TOP #(
        .CLK_N_EXT ( 1             ),   // falling-edge registers on clk_cpu_n (global clock)
`ifdef ST_030_CACHES
        .CACHES    ( 1             )    // experimental I/D caches (incomplete), CACR EI/ED
`else
        .CACHES    ( 0             )    // no caches, as a TF534/TF536 with ST-RAM (default)
`endif
    ) i_wf68k30l (
`endif
        .CLK       ( clk_cpu       ),
        .CLK_N     ( clk_cpu_n     ),
        .ADR_OUT   ( cpu_adr       ),
        .DATA_IN   ( cpu_din       ),
        .DATA_OUT  ( cpu_dout      ),
        .DATA_EN   (               ),
        .BERRn     ( cpu_berrn     ),
        .RESET_INn ( cpu_rst_n     ),
        .RESET_OUT ( cpu_reset_out ),
        .HALT_INn  ( cpu_rst_n     ),
        .HALT_OUTn ( cpu_halt_outn ),
        .FC_OUT    ( cpu_fc        ),
        .AVECn     ( cpu_avecn     ),
        .IPLn      ( ipl_r         ),
        .IPENDn    ( cpu_ipendn    ),   // FalconFPGA DIAG (was open)
        .DSACKn    ( cpu_dsackn    ),
        .SIZE      ( cpu_size      ),
        .ASn       ( cpu_asn       ),
        .RWn       ( cpu_rwn       ),
        .RMCn      ( cpu_rmcn      ),
        .DSn       ( cpu_dsn       ),
        .ECSn      (               ),
        .OCSn      (               ),
        .DBENn     (               ),
        .BUS_EN    (               ),
        .STERMn    ( 1'b1          ),
        .STATUSn   ( cpu_statusn   ),   // FalconFPGA DIAG (was open)
        .REFILLn   (               ),
        .BRn       ( 1'b1          ),   // arbitration is done on the ST side
        .BGn       (               ),
        .BGACKn    ( 1'b1          )
    );

    // ---- front end: request capture (clk_32) -------------------------------
    // clk_cpu is phase-locked to clk_32 (same PLL VCO, every clk_cpu edge is a
    // clk_32 rising edge), so the 030 outputs are sampled directly by clk_32
    // (timed related-clock paths, no synchroniser): the request is seen on
    // the first clk_32 edge after the 030 asserts AS (31.25 ns).
    reg        c_open  = 1'b0;
    reg        c_req_t = 1'b0;
    reg [23:0] c_adr   = 24'd0;
    reg [7:0]  c_adr_hi = 8'd0;   // FalconFPGA DIAG: A31:24 (not used on the ST bus)
    reg [1:0]  c_size  = 2'b00;
    reg        c_rwn   = 1'b1;
    reg [2:0]  c_fc    = 3'd0;
    reg [15:0] c_wdata = 16'd0;

    always @(posedge clk) begin
        if (!cpu_rst_n || cpu_asn) begin
            c_open <= 1'b0;
        end else if (!c_open) begin
            // first clk_32 edge with AS low. Address, SIZE, RW, FC and the
            // write data mux are registered by the 030 with AS (S0).
            c_open  <= 1'b1;
            c_req_t <= ~c_req_t;
            c_adr   <= cpu_adr[23:0];     // A31:24 ignored: 24-bit ST bus
            c_adr_hi <= cpu_adr[31:24];   // FalconFPGA DIAG only
            c_size  <= cpu_size;
            c_rwn   <= cpu_rwn;
            c_fc    <= cpu_fc;
            c_wdata <= cpu_dout[31:16];   // 16-bit port: D31:24 even, D23:16 odd
        end
    end

    // ---- terminations back to the 030 ------------------------------------
    // s_* are clk_32 registers, read by the 030 directly (its DSACK/AVEC/BERR
    // input registers sample on the falling clk_cpu edge = a clk_32 rising
    // edge; timed related-clock paths). The tag stops the 030 from seeing the
    // previous cycle's termination, c_open drops one clk_32 after AS goes high.
    // DSACK for a DTACK-terminated cycle is given early, on the edge where a
    // 68000 samples DTACK (en2 in S4): the 030 samples DSACK on its next
    // falling edge (>= 31.25 ns later) and latches the data one clk_cpu later
    // (>= 156.25 ns after that en2), while s_rdata is written 125 ns after it
    // (S6 en2, the 68000 data latch edge). The s_rdata -> 030 data register
    // path is a timed clk_32 -> clk_cpu_n path (>= 31.25 ns).
    reg        s_tag    = 1'b0;
    reg        s_dsack  = 1'b0;
    reg        s_avec   = 1'b0;
    reg        s_berr   = 1'b0;
    reg [15:0] s_rdata  = 16'hffff;

    wire term_ok = c_open & (s_tag == c_req_t);
    assign cpu_dsackn = (term_ok & s_dsack) ? 2'b01 : 2'b11;
    assign cpu_avecn  = ~(term_ok & s_avec);
    assign cpu_berrn  = ~(term_ok & s_berr);
    assign cpu_din    = {s_rdata, s_rdata};

    // =====================================================================
    // clk_32 domain: the 68000 side
    // =====================================================================
    always @(posedge clk) ipl_r <= {IPL2n, IPL1n, IPL0n};

    (* syn_preserve = 1 *) reg [1:0] rmc_sync = 2'b11;
    (* syn_preserve = 1 *) reg [1:0] rsto_sync = 2'b00;
    (* syn_preserve = 1 *) reg [1:0] hlt_sync = 2'b11;
    always @(posedge clk) begin
        rmc_sync  <= {rmc_sync[0], cpu_rmcn};
        rsto_sync <= {rsto_sync[0], cpu_reset_out};
        hlt_sync  <= {hlt_sync[0], cpu_halt_outn};
    end
    wire req_now  = c_req_t;   // clk_32 register (no synchroniser needed)
    assign dbg_run   = cpu_rst_n;   // FalconFPGA DIAG
    assign dbg_req   = req_now;
    assign dbg_dsack = s_dsack;
    assign dbg_berr  = s_berr;
    assign oRESETn  = ~rsto_sync[1];
    assign oHALTEDn = hlt_sync[1];
    wire rmc_lock = ~rmc_sync[1];

    reg  s_seen = 1'b0;
    // F61: a request is also seen live, on the first clk_32 edge where the
    // 030's AS is low (the edge that opens c_open), straight from the 030's
    // AS/address/SIZE/RW/FC/data outputs (related-clock paths, 31.25 ns). An
    // en1 on that edge starts the ST cycle at once instead of one clk_32
    // later, so the 030 can follow a cycle that ends at S6 with the next S0.
    // q_* are the request fields: live on that edge, captured (c_*) after it.
    wire live    = cpu_rst_n & ~cpu_asn & ~c_open;
    wire pending = live | (req_now != s_seen);
    wire        q_tag  = live ? ~c_req_t        : c_req_t;
    wire [23:0] q_adr  = live ? cpu_adr[23:0]   : c_adr;
    wire [1:0]  q_size = live ? cpu_size        : c_size;
    wire        q_rwn  = live ? cpu_rwn         : c_rwn;
    wire [2:0]  q_fc   = live ? cpu_fc          : c_fc;
    wire [15:0] q_wdata = live ? cpu_dout[31:16] : c_wdata;
    // request fields are stable: they were written together with the toggle
    // TF534 (Stephen J. Leary), rtl/bus_top.v: CPU space (FC=7) with A19:16=F
    // is an interrupt acknowledge; other CPU-space cycles are not passed on.
    wire req_cpu_space = (q_fc == 3'b111);
    wire req_iack      = req_cpu_space & (q_adr[19:16] == 4'hF);
    wire req_bad_space = req_cpu_space & ~req_iack;

    // ---- input sampling like a 68000 (DTACK/BERR on en2, VPA/BR/BGACK en1)
    // TF534 (Stephen J. Leary), rtl/bus_delay.v: DTACK is delayed (one stage
    // in its ATARI build) before the 030 is terminated; here it is registered.
    reg rDtack = 1'b1, rBerr = 1'b1, Vpai = 1'b1, BRi = 1'b1, BgackI = 1'b1;
    always @(posedge clk) begin
        if (enPhi2) begin
            rDtack <= DTACKn;
            rBerr  <= BERRn;
        end
        if (enPhi1) begin
            Vpai   <= VPAn;
            BRi    <= BRn;
            BgackI <= BGACKn;
        end
    end

    // ---- bus phases (advance on en1): IDLE, S0, S2, S4 (waits), S6 ---------
    localparam [2:0] P_IDLE = 3'd0, P_S0 = 3'd1, P_S2 = 3'd2, P_S4 = 3'd3, P_S6 = 3'd4;
    localparam [1:0] R_DSACK = 2'd0, R_AVEC = 2'd1, R_BERR = 2'd2;

    reg [2:0]  phase  = P_IDLE;
    reg        rAS = 1'b1, rUDS = 1'b1, rLDS = 1'b1, rRWn = 1'b1;
    reg [23:1] r_adr  = 23'h7fffff;
    reg [2:0]  r_fc   = 3'b111;
    reg [15:0] r_dout = 16'hffff;
    reg        r_write = 1'b0, r_uds = 1'b0, r_lds = 1'b0, r_iack = 1'b0, r_tag = 1'b0;
    reg        addr_oe = 1'b0;
    reg [1:0]  r_res  = R_DSACK;
    reg        iStop  = 1'b0;
    reg [3:0]  eCntr  = 4'd0;
    reg        rVma   = 1'b1;

    // arbitration (68000 style, BG changes on en1, state on en2)
    // TF534 (Stephen J. Leary), rtl/arb.v: BG is only passed to another bus
    // master when the 68000 side is idle (bg_block below).
    localparam [1:0] A_IDLE = 2'd0, A_GRANT = 2'd1, A_BUSY = 2'd2;
    reg [1:0] arb = A_IDLE;
    reg [1:0] arb_nx;
    reg       granting = 1'b0;
    wire bg_block  = (phase == P_S0) | rmc_lock;   // no grant while a cycle starts or during RMC
    wire bus_avail = BRi & BgackI & (arb == A_IDLE);

    always @* begin
        arb_nx = arb;
        case (arb)
        A_IDLE:  if (~BgackI)               arb_nx = A_BUSY;    // taken without BR
                 else if (~BRi & ~bg_block) arb_nx = A_GRANT;
        A_GRANT: if (~BgackI)               arb_nx = A_BUSY;    // master took the bus
                 else if (BRi)              arb_nx = A_IDLE;    // request withdrawn
        A_BUSY:  if (BgackI)                arb_nx = (~BRi & ~bg_block) ? A_GRANT : A_IDLE;
        default:                            arb_nx = A_IDLE;
        endcase
    end
    // BG is asserted in GRANT, and also in BUSY when another master already
    // requests again (68000 behaviour for chained masters)
    wire grant_nx = (arb_nx == A_GRANT) | ((arb_nx == A_BUSY) & ~BRi & ~bg_block);
    wire can_start = pending & ~req_bad_space & bus_avail;   // (CPU space: c_* path above)
    // A23:20 == E is the 256K map. FC/FD/FE is the 192K map.
    wire req_rom = (q_adr[23:20] == 4'hE) |
                   (q_adr[23:16] == 8'hFC) | (q_adr[23:16] == 8'hFD) |
                   (q_adr[23:16] == 8'hFE);


    // UDS/LDS from A0 and SIZE: 16-bit port
    // TF534 (Stephen J. Leary), rtl/bus_top.v: these equations are his.
    wire req_uds = ~q_adr[0];
    wire req_lds =  q_adr[0] | (q_size != 2'b01);

    assign ASn  = rAS;
    assign ASEn = ~(phase == P_S0);
    assign UDSn = rUDS;
    assign LDSn = rLDS;
    assign eRWn = rRWn;
    assign VMAn = rVma;
    assign {FC2, FC1, FC0} = r_fc;
    assign eab  = r_adr;
    assign oEdb = r_dout;

    wire xVma = ~rVma & (eCntr == 4'd8);

    always @(posedge clk) begin
        if (pwrUp) begin
            E     <= 1'b0;
            eCntr <= 4'd0;
            rVma  <= 1'b1;
        end else begin
            // E: 10 en2 periods, 6 low / 4 high (68000 E clock)
            // TF534 (Stephen J. Leary), rtl/m6800.v: 10-state E counter, VMA
            // asserted for VPA cycles and the cycle ended at the E edge.
            if (enPhi2) begin
                if (eCntr == 4'd9)      E <= 1'b0;
                else if (eCntr == 4'd5) E <= 1'b1;
                eCntr <= (eCntr == 4'd9) ? 4'd0 : eCntr + 4'd1;
            end
            if (enPhi2 & addr_oe & ~Vpai & (eCntr == 4'd3))
                rVma <= 1'b0;
            else if (enPhi1 & (eCntr == 4'd0))
                rVma <= 1'b1;
        end
    end

    always @(posedge clk) begin
        if (extReset | pwrUp) begin
            phase   <= P_IDLE;
            rAS     <= 1'b1;
            rUDS    <= 1'b1;
            rLDS    <= 1'b1;
            rRWn    <= 1'b1;
            addr_oe <= 1'b0;
            iStop   <= 1'b0;
            s_seen  <= req_now;
            s_dsack <= 1'b0;
            s_avec  <= 1'b0;
            s_berr  <= 1'b0;
            arb     <= A_IDLE;
            granting <= 1'b0;
            BGn       <= 1'b1;
            rom_fetch <= 1'b0;
        end else begin
            // ---- arbitration: state on en2, BG output on en1 ----
            if (enPhi2) begin
                arb      <= arb_nx;
                granting <= grant_nx;
            end
            if (enPhi1)
                BGn <= ~granting;

            // ---- CPU-space cycles other than IACK: BERR, no ST cycle ----
            if (pending & ~live & req_bad_space) begin   // captured (c_*) request only
                s_seen  <= req_now;
                s_tag   <= req_now;
                s_dsack <= 1'b0;
                s_avec  <= 1'b0;
                s_berr  <= 1'b1;
            end

            // ---- termination sampling like the 68000 ----
            if (enPhi2)
                iStop <= xVma | (Vpai & ~rBerr);

            // early DSACK (see terminations): DTACK seen on the 68000's S4
            // sample edge (en2 in S4, the edge that also loads rDtack)
            // At 16 MHz the 030 would latch the data 94 ns after en2, before
            // S6 en2, so DSACK is given one phase later (S4 -> S6 en1).
            // F61: also at 16 MHz. The read word is taken on the en1 edge
            // that enters S6 (below), 31.25 ns before the 030's data latch
            // edge (>= 93.75 ns after this en2).
            if (enPhi2 & (phase == P_S4) & ~DTACKn) begin
                s_tag   <= r_tag;
                s_dsack <= 1'b1;
            end
            if (enPhi1 & (phase == P_S4) & ~rDtack)
                s_rdata <= iEdb;

            if (enPhi2 & (phase == P_S0))
                addr_oe <= 1'b1;

            // ---- S6 en2: negate AS/DS, latch data, answer the 030 ----
            if (enPhi2 & (phase == P_S6)) begin
                rAS     <= 1'b1;
                rUDS    <= 1'b1;
                rLDS    <= 1'b1;
                if (r_res != R_DSACK | rDtack)   // VPA/E cycle, IACK vector, BERR
                    s_rdata <= iEdb;
                s_tag   <= r_tag;
                s_dsack <= (r_res == R_DSACK);
                s_avec  <= (r_res == R_AVEC);
                s_berr  <= (r_res == R_BERR);
            end

            if (enPhi1) begin
                case (phase)
                P_S0: begin
                    phase <= P_S2;
                    rAS   <= 1'b0;
                    if (r_write) rRWn <= 1'b0;
                    else begin
                        rUDS <= ~r_uds;
                        rLDS <= ~r_lds;
                    end
                end
                P_S2: begin
                    phase <= P_S4;
                    if (r_write) begin
                        rUDS <= ~r_uds;
                        rLDS <= ~r_lds;
                    end
                end
                P_S4: begin
                    if (~rDtack | iStop) begin
                        phase <= P_S6;
                        if (~rDtack)    r_res <= R_DSACK;
                        else if (~rVma) r_res <= r_iack ? R_AVEC : R_DSACK; // VPA/E cycle (terminated at S6)
                        else            r_res <= R_BERR;
                    end
                end
                default: ;   // P_IDLE / P_S6 handled below
                endcase

                if (phase == P_S6) begin
                    rRWn    <= 1'b1;
                    addr_oe <= 1'b0;
                    phase   <= P_IDLE;
                end

                if ((phase == P_IDLE | phase == P_S6) & can_start) begin
                    if (req_rom) rom_fetch <= 1'b1;
                    // accept the 030 request: 68000 S0
                    phase   <= P_S0;
                    s_seen  <= q_tag;
                    s_dsack <= 1'b0;
                    s_avec  <= 1'b0;
                    s_berr  <= 1'b0;
                    r_tag   <= q_tag;
                    r_adr   <= q_adr[23:1];
                    r_fc    <= q_fc;
                    r_write <= ~q_rwn;
                    r_dout  <= q_wdata;
                    r_uds   <= req_uds;
                    r_lds   <= req_lds;
                    r_iack  <= req_iack;
                end
            end
        end
    end

    // ---- FalconFPGA DIAG diag030b: first-BERR latch (clk_32) ----
    // Observation only. The 030 waits for its termination, so c_* still hold
    // the faulting request when s_berr is set (both BERR paths).
    wire d_berr_now = (pending & req_bad_space) |
                      (enPhi2 & (phase == P_S6) & (r_res == R_BERR));
    reg        d_got   = 1'b0;
    reg [6:0]  d_info  = 7'd0;    // FC2:0, RW, SIZE1:0, bad_space
    reg [31:0] d_badr  = 32'd0;
    always @(posedge clk) begin
        if (extReset | pwrUp) begin
            d_got  <= 1'b0;
            d_info <= 7'd0;
            d_badr <= 32'd0;
        end else if (d_berr_now & ~d_got) begin
            d_got  <= 1'b1;
            d_info <= {c_fc, c_rwn, c_size, req_bad_space};
            d_badr <= {c_adr_hi, c_adr};
        end
    end

    // ---- FalconFPGA DIAG diag030c: 030 bus-cycle watch (clk_32 since F58) ----
    // Taken straight from the WF68K30L outputs (cpu_adr/cpu_fc/...), on the
    // same clk_cpu edge where the front end opens a request (c_open 0->1),
    // independent of c_adr (diag030b's PC rows read A20:18 as 0).
    wire x_start = cpu_rst_n & ~cpu_asn & ~c_open;
    wire x_term  = ~cpu_asn & ((cpu_dsackn != 2'b11) | ~cpu_berrn | ~cpu_avecn);
    reg [31:0] x_adr   = 32'd0;   // last started cycle A31:0
    reg [2:0]  x_fc    = 3'd0;
    reg        x_rwn   = 1'b1;
    reg [1:0]  x_size  = 2'b00;
    reg        x_done  = 1'b1;    // last started cycle has been terminated
    reg        x_hung  = 1'b0;    // sticky: one cycle open > 2^13 clk_cpu (~1 ms)
    reg [15:0] x_tmr   = 16'd0;   // F58: clk_32 (2^15 = ~1 ms)
    reg [2:0]  x_tres  = 3'd0;    // last termination {DSACK, BERR, AVEC}
    reg        x_iack_s = 1'b0, x_iack_d = 1'b0, x_cpusp = 1'b0, x_iack_av = 1'b0;
    reg [23:0] x_pc    = 24'd0;   // live last program fetch A23:0
    reg [7:0]  x_cnt   = 8'd0;    // bus cycles started (mod 256)
    wire       x_iack_now = (cpu_fc == 3'b111) & (cpu_adr[19:16] == 4'hF);
    always @(posedge clk) begin
        if (!cpu_rst_n) begin
            x_adr <= 32'd0;  x_fc <= 3'd0;  x_rwn <= 1'b1;  x_size <= 2'b00;
            x_done <= 1'b1;  x_hung <= 1'b0;  x_tmr <= 16'd0;  x_tres <= 3'd0;
            x_iack_s <= 1'b0;  x_iack_d <= 1'b0;  x_cpusp <= 1'b0;  x_iack_av <= 1'b0;
            x_pc <= 24'd0;  x_cnt <= 8'd0;
        end else begin
            if (x_start) begin
                x_adr  <= cpu_adr;
                x_fc   <= cpu_fc;
                x_rwn  <= cpu_rwn;
                x_size <= cpu_size;
                x_done <= 1'b0;
                x_tmr  <= 14'd0;
                x_cnt  <= x_cnt + 8'd1;
                if (cpu_fc[1:0] == 2'b10) x_pc <= cpu_adr[23:0];
                if (cpu_fc == 3'b111) x_cpusp <= 1'b1;
                if (x_iack_now) x_iack_s <= 1'b1;
            end else if (!x_done) begin
                if (x_term) begin
                    x_done <= 1'b1;
                    x_tres <= {(cpu_dsackn != 2'b11), ~cpu_berrn, ~cpu_avecn};
                    if ((x_fc == 3'b111) & (x_adr[19:16] == 4'hF)) begin
                        x_iack_d <= 1'b1;
                        if (~cpu_avecn) x_iack_av <= 1'b1;
                    end
                end else if (~x_tmr[15])
                    x_tmr <= x_tmr + 16'd1;
                else
                    x_hung <= 1'b1;
            end
        end
    end
    wire x_inprog = ~x_done & ~cpu_asn;
    wire [31:0] row_d = {
        x_fc, x_rwn,                                  // G1
        x_size, x_inprog, x_hung,                     // G2
        x_tres, 1'b0,                                 // G3 DSACK BERR AVEC -
        x_iack_s, x_iack_d, x_cpusp, x_iack_av,       // G4
        cpu_halt_outn, cpu_reset_out, cpu_rst_n, cpu_ipendn,   // G5
        cpu_statusn, ipl_r,                           // G6 STATUSn IPL2n:0n
        cpu_asn, cpu_dsn, cpu_dsackn,                 // G7 ASn DSn DSACK1n DSACK0n
        cpu_berrn, cpu_avecn, cpu_rmcn, cpu_rwn       // G8
    };
    wire [31:0] row_e = {
        phase, pending,                               // G1
        req_now, s_seen, c_open, term_ok,             // G2
        rAS, rUDS, rLDS, rRWn,                        // G3
        rDtack, rBerr, Vpai, iStop,                   // G4
        s_dsack, s_avec, s_berr, s_tag,               // G5
        r_tag, addr_oe, rVma, r_iack,                 // G6
        arb, BGn, can_start,                          // G7
        r_res, BRi, BgackI                            // G8
    };
    assign dbg_trace = {d_got, d_info, d_badr, x_adr, row_d, row_e, x_cnt, x_pc};

endmodule

`default_nettype wire
